from server.prompt_text import (
    COLORIZE_IMAGES_TOOL_DESCRIPTION,
    CROP_IMAGES_TOOL_DESCRIPTION,
    RUN_PROMPT_WORKFLOW_TOOL_DESCRIPTION,
)


TOOL_DESCRIPTIONS = {
    "crop_images": CROP_IMAGES_TOOL_DESCRIPTION,
    "colorize_images": COLORIZE_IMAGES_TOOL_DESCRIPTION,
    "run_prompt_workflow": RUN_PROMPT_WORKFLOW_TOOL_DESCRIPTION,
}
